require("jorge.options")
require("jorge.remap")
require("jorge.commands")
require("jorge.lazy")
require("jorge.jj")
require("jorge.wf").setup()
require("jorge.pi_edit_rpc").setup()
require("jorge.breadcrumbs").setup({ prefix = "@" })
